services:
    _defaults:
        bind:
            PoP\LooseContracts\LooseContractManagerInterface: '@loose_contract_manager'
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    PoP\Application\ModuleFilters\:
        resource: '../src/ModuleFilters/*'

    PoP\Application\Hooks\:
        resource: '../src/Hooks/*'
        public: true

    PoP\Application\LooseContracts\:
        resource: '../src/LooseContracts/*'
        public: true

    engine:
        class: \PoP\Application\Engine\Engine
        public: true
