services:
    PoP\Application\ModuleFilters\:
        resource: '../src/ModuleFilters/*'

    PoP\Application\Hooks\:
        resource: '../src/Hooks/*'
        public: true

    PoP\Application\LooseContracts\:
        resource: '../src/LooseContracts/*'
        public: true
