services:
    _defaults:
        bind:
            PoP\LooseContracts\Contracts\LooseContractManagerInterface: '@loose_contract_manager'
            PoP\Hooks\Contracts\HooksAPIInterface: '@hooks_api'
            PoP\Translation\Contracts\TranslationAPIInterface: '@translation_api'

    PoP\Application\ModuleFilters\:
        resource: '../src/ModuleFilters/*'

    PoP\Application\Hooks\:
        resource: '../src/Hooks/*'
        public: true

    PoP\Application\LooseContracts\:
        resource: '../src/LooseContracts/*'
        public: true
